name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GIT_SHA: "$(git rev-parse --short HEAD)"
  REGISTRY_USER: funman

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
        docker build -f Dockerfile -t funman/demo:latest ./
        
        docker tag funman/demo:latest funman/demo:$GIT_SHA
        
        docker push funman/demo:latest
        
        docker push funman/demo:$GIT_SHA
      
