name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GIT_SHA: "$(git rev-parse --short HEAD)"
  REGISTRY_USER: funman

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Dockerfile
      run: docker build -f Dockerfile -t funman/demo:latest ./
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'funman/demo:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
          
    - name: Push latest 
      run: docker push funman/demo:latest
    - name: Docker tag    
      run: docker tag funman/demo:latest funman/demo:${{env.GIT_SHA}}
    - name: Push Git SHA    
      run: docker push funman/demo:${{env.GIT_SHA}}
   
      
